# .cnb.yml
$:
  vscode:
    - runner:
        cpus: 16
      docker:
        image:
          name: docker.cnb.cool/xuanzhi33/dev-env:latest
      services:
        - docker
        - vscode
      env:
        CNB_WELCOME_CMD: pnpm i
      stages:
        - name: ls
          script: ls